- name: file level variables
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
    - name: print variables
      vars:
        COURSE: "Ansible"
      ansible.builtin.debug:
        msg: "I am learning {{ COURSE }} with {{ Trainer }} for a {{ Duration }}"