- name: play level variables
  hosts: local
  connection: local
  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "I am learning {{ COURSE }} with {{ Trainer }} for a {{ Duration }}"