- name: install packages using loop
  hosts: local
  connection: local
  become: yes
  tasks:
    # - name: install package
    #   ansible.builtin.package:
    #     name: "{{ item }}"
    #     state: present
    #   loop:
    #     - nginx
    #     - mysql
    #     - zip

    - name: install package # Above and this is the same here we looped the state var also 
      ansible.builtin.package:
         name: " {{ item.name }}"
         state: "{{ item.state }}"
      loop:
        - {name: "mysql", state: "present" }
        - {name: "nginx", state: "absent" }
        - {name: "zip", state: "present" }