- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: linux, ansible, shell, aws
    tagsMap:
       name: "ansible"
       project: "roboshop"
       compnent: "catalogue"
    tagsList: [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "compnent",
            "value": "catalogue"
        }
    ]
      #  - {"key":"name", "value": "ansible"}
      #  - {"key":"name", "value": "roboshop"}
      #  - {"key":"name", "value": "catalogue"}
  tasks:
    - name: Filters example
      ansible.builtin.debug:
        msg: "Hi Mani, {{ GREETING | default('Good day')  }}" # Making variables optinal or providing default values
    
    - name: Filter example - 2
      ansible.builtin.debug:
        msg: "{{ topics | split(',') }}"  # string to list 

    - name: map to list
      ansible.builtin.debug:
        msg: "{{ tagsMap | dict2items }}"

    - name: list/item to map
      ansible.builtin.debug:
        msg: "{{ tagsList | items2dict }}"
       